config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :accommodations
  end

  resources :accommodations
end

app/models/accommodation.rb
# == Schema Information
#
# Table name: accommodations
#
#  id             :bigint           not null, primary key
#  name           :string           not null
#  estate_type    :string           not null
#  share_type     :string           not null
#  summary        :string
#  description    :text
#  num_of_room    :integer
#  guest_capicity :integer
#  num_of_bed     :integer
#  num_of_toilet  :integer
#  country        :string
#  state          :string
#  city           :string
#  district       :string
#  street         :string
#  number         :string
#  building       :string
#  room           :string
#  latitude       :string
#  longitude      :string
#  user_id        :bigint
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Accommodation < ApplicationRecord
  enum estate_type: {
    'apartment': 'apartment',
    'house': 'house',
    'villa': 'villa'
  }

  enum share_type: {
    'whole_building': 'whole_building',
    'room': 'room'
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  name                   :string           default(""), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :rememberable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :trackable

  validates :name, :email, presence: true
end

app/controllers/admin/accommodations_controller.rb
module Admin
  class AccommodationsController < ApplicationController
    before_action :set_accommodation, only: [:show, :edit, :update, :destroy]

    # GET /accommodations
    # GET /accommodations.json
    def index
      @accommodations = Accommodation.all
    end

    # GET /accommodations/1
    # GET /accommodations/1.json
    def show
    end

    # GET /accommodations/new
    def new
      @accommodation = Accommodation.new
    end

    # GET /accommodations/1/edit
    def edit
    end

    # POST /accommodations
    # POST /accommodations.json
    def create
      @accommodation = Accommodation.new(accommodation_params)

      respond_to do |format|
        if @accommodation.save
          format.html { redirect_to @accommodation, notice: 'accommodation was successfully created.' }
          format.json { render :show, status: :created, location: @accommodation }
        else
          format.html { render :new }
          format.json { render json: @accommodation.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /accommodations/1
    # PATCH/PUT /accommodations/1.json
    def update
      respond_to do |format|
        if @accommodation.update(accommodation_params)
          format.html { redirect_to @accommodation, notice: 'accommodation was successfully updated.' }
          format.json { render :show, status: :ok, location: @accommodation }
        else
          format.html { render :edit }
          format.json { render json: @accommodation.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /accommodations/1
    # DELETE /accommodations/1.json
    def destroy
      @accommodation.destroy
      respond_to do |format|
        format.html { redirect_to accommodations_url, notice: 'accommodation was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_accommodation
        @accommodation = Accommodation.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def accommodation_params
        params.fetch(:accommodation, {})
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/accommodations_helper.rb
module AccommodationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/accommodations/_form.html.slim
= form_with(model: accommodation, local: true) do |form|
  - if accommodation.errors.any?
    div#error_explanation"
      h2 = "#{pluralize(accommodation.errors.count, "error")} prohibited this accommodation from being saved:"
      ul
        - accommodation.errors.full_messages.each do |message|
          li = message
  div
    = form.label :estate_type
    = select(:accommodation, :estate_type, Accommodation.estate_types.to_a)
    = form.label :share_type
    = select(:accommodation, :share_type, Accommodation.share_types.to_a)
    = form.label :summary
    = form.text_field :summary
    = form.label :description
    = form.text_area :description

  div.actions
    = form.submit
  

app/views/admin/accommodations/edit.html.erb
<h1>Editing accommodation</h1>

<%= render 'form', accommodation: @accommodation %>

<%= link_to 'Show', @accommodation %> |
<%= link_to 'Back', admin_accommodations_path %>

app/views/admin/accommodations/index.html.slim
p#notice 
  = notice

h1 accommodations

table
  thead
    tr
      th
      th colspan="3" Operations

  tbody
    - @accommodations.each do |accommodation|
      tr
        td = accommodation.estate_type
        td = accommodation.share_type
        td = link_to 'Show', admin_accommodation_path(accommodation)
        td = link_to 'Edit', edit_admin_accommodation_path(accommodation)
        td = link_to 'Destroy', admin_accommodation_path(accommodation), method: :delete, data: { confirm: 'Are you sure?' }

br

= link_to 'New accommodation', new_admin_accommodation_path

app/views/admin/accommodations/new.html.erb
<h1>New accommodation</h1>

<%= render 'form', accommodation: @accommodation %>

<%= link_to 'Back', admin_accommodations_path %>

app/views/admin/accommodations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_accommodation_path(@accommodation) %> |
<%= link_to 'Back', admin_accommodations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MimicAir</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>